project:
  type: website

execute:
  freeze: auto

website:
  title: "Price Statistics Reproducibility Project"
  repo-url: https://github.com/UN-Task-Team-for-Scanner-Data/reproducibility-project
  issue-url: https://github.com/UN-Task-Team-for-Scanner-Data/reproducibility-project/issues/new
  repo-actions: [source, issue]
  favicon: docs/images/logo.png
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  page-footer:
    center:
      - text: "About"
        href: docs/about.qmd
      - text: "FAQ"
        href: docs/faq.qmd
  navbar:
    background: primary
    logo: docs/images/logo.png
    search: true
    title: "Price Statistics Reproducibility Project"
    left:
      - href: docs/index.qmd
        text: Home
      - text: "Reproducibility Guidance"
        menu:
          - href: docs/reproducibility-guidance/intro.qmd
          - href: docs/reproducibility-guidance/citing-code.qmd
          - href: docs/reproducibility-guidance/citing-data.qmd
      - text: "Open Data"
        menu:
          - href: docs/datasets-guidance/catalogue.qmd
          - href: docs/datasets-guidance/opening-up-datasets.qmd

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Site work is being developed** - this website is will have its soft launch at [2025 Meeting of the Group of Experts on Consumer Price Indices](https://unece.org/info/events/event/394156). Please come back soon!"
    type: secondary
    position: below-navbar
      
    tools:
      - icon: globe
        href: https://unstats.un.org/wiki/display/GWGSD/Handbook+on+utilising+new+data+sources+in+the+production+of+consumer+price+statistics
        text: "UN Task Team e-handbook home"
      - icon: person-raised-hand
        href: https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml
        text: "Find out more about the UN Task Team"


format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: cyborg
    css: docs/styles.css
