project:
  type: website

execute:
  freeze: auto

website:
  title: "Price Statistics Reproducibility Project"
  repo-url: https://github.com/UN-Task-Team-for-Scanner-Data/reproducibility-project
  issue-url: https://github.com/UN-Task-Team-for-Scanner-Data/reproducibility-project/issues/new
  repo-actions: [source, issue]
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  navbar:
    background: primary
    search: true
    title: "Price Statistics Reproducibility Project"
    left:
      - href: index.qmd
        text: Home
      - text: "Reproducibility Guidance"
        menu:
          - docs/datasets-guidance/intro.qmd
          - docs/datasets-guidance/code.qmd
          - docs/datasets-guidance/citing-code.qmd
      - text: "Open Datasets"
        menu:
          - docs/datasets-guidance/intro.qmd
          - docs/datasets-guidance/catalogue.qmd
          - docs/datasets-guidance/how-to-cite.qmd

      
    tools:
      - icon: globe
        href: https://unstats.un.org/wiki/display/GWGSD/Handbook+on+utilising+new+data+sources+in+the+production+of+consumer+price+statistics
        text: "UN Task Team e-handbook home"
      - icon: person-raised-hand
        href: https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml
        text: "Find out more about the UN Task Team"


format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: cyborg
    css: docs/styles.css