project:
  type: website

execute:
  freeze: auto

website:
  title: "Price Statistics Reproducibility Project"
  repo-url: https://github.com/UN-Task-Team-for-Scanner-Data/reproducibility-project
  issue-url: https://github.com/UN-Task-Team-for-Scanner-Data/reproducibility-project/issues/new
  repo-actions: [source, issue]
  favicon: docs/images/logo.png
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  draft-mode: visible
  page-footer:
    center:
      - text: "About"
        href: docs/about.qmd
      - text: "FAQ"
        href: docs/faq.qmd
  navbar:
    background: primary
    logo: docs/images/logo.png
    logo-href: https://un-task-team-for-scanner-data.github.io/reproducibility-project/docs/
    search: true
    title: "Price Statistics Reproducibility Project"

    right:
      - icon: globe
        href: https://unstats.un.org/wiki/display/GWGSD/Handbook+on+utilising+new+data+sources+in+the+production+of+consumer+price+statistics
      - icon: person-raised-hand
        href: https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml
    left:
      - href: docs/index.qmd
        text: Home
      - text: "How to be reproducible"
        href: docs/reproducibility-guidance/intro.qmd
      - text: "Data Catalogue"
        href: docs/catalogue/catalogue.qmd
      - text: "About"
        menu:
          - docs/about.qmd
          - docs/faq.qmd
  sidebar:
    - id: reproducibility-guidance
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: Getting started
          contents:
          - docs/reproducibility-guidance/intro.qmd
          - docs/reproducibility-guidance/how-to-start.qmd
        - "---"
        - section: "Guides and how-tos"
          contents:
            - section: "The research compendium"
              contents:
              - docs/reproducibility-guidance/howtos/research-compendium-structure.qmd
              - docs/reproducibility-guidance/howtos/licences.qmd
            - section: "The data"
              contents:
              - docs/reproducibility-guidance/howtos/input-data.qmd
              - docs/reproducibility-guidance/howtos/synthetic-data.qmd
              - docs/reproducibility-guidance/howtos/opening-data.qmd
            - section: "Publishig artifacts and citation"
              contents:
                - docs/reproducibility-guidance/howtos/how-to-cite-digital-objects.qmd
                - docs/reproducibility-guidance/howtos/metadata.qmd
                - docs/reproducibility-guidance/howtos/publishing-research-compendium.qmd
                - docs/reproducibility-guidance/howtos/citing-code.qmd
                - docs/reproducibility-guidance/howtos/citing-data.qmd
        - "---"
        - title: Other useful resources
          href: docs/reproducibility-guidance/open-material.qmd
    - id: data-catalogue
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - docs/catalogue/catalogue.qmd
        - "---"
        - section: "About the catalogue"
          contents:
          - docs/catalogue/about.qmd
          - docs/catalogue/contributing.qmd

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**This site shows interim guidance. We are actively updating this site. See our [project charter](https://github.com/UN-Task-Team-for-Scanner-Data/reproducibility-project/blob/main/project-content/project-charter.md) and [the GitHub project](https://github.com/orgs/UN-Task-Team-for-Scanner-Data/projects/1) for more info about what we are working on."
    type: secondary
    position: below-navbar
      



format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: cyborg
    css: docs/styles.css
